site_name: Tiled2Unity 
docs_dir: doc
pages:
- 'index.md'
- 'Getting Started' : 'getting-started.md'
- 'Fixing Seams' : 'fixing-seams.md'
- 'Dealing With Texture Name Collisions' : 'prepostfix.md'
theme: readthedocs